--- #YAML:1.0
name:                MooseX-Blessed-Reconstruct
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Class::MOP:                    0.66
    Data::Visitor:                 0.21
    Moose:                         0
    namespace::clean:              0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
